<div class="container">
    <div class="login">
        <div class="center"><img src="<?php echo $this->basePath('img/login/LogoLogin.png') ?>" alt="Nyshu"></div>
        <?php
        $form = $this->userForm;
        $form->setAttribute('action', $this->url('panel-login', array('action' => 'login')));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <div class="row">
            <div class="input-field col s2 offset-s4">
                <i class="mdi-action-account-circle prefix"></i>
                <?php  echo $this->formText($form->get('user_name')); ?>
                <?php  echo $this->formLabel($form->get('user_name'));
                $showError=$this->formElementErrors($form->get('user_name'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
            <div class="input-field col s2 ">
                <i class="mdi-action-lock prefix"></i>
                <?php  echo $this->formPassword($form->get('user_password')); ?>
                <?php  echo $this->formLabel($form->get('user_password'));
                $showError=$this->formElementErrors($form->get('user_password'));
                if(!empty($showError)):
                    ?>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                <?php  endif;?>
            </div>
        </div>
        <div class="center input-field col s6">
            <?php  echo $this->formButton($form->get('submit')); ?>
        </div>
        <?php
        //echo $this->formCollection($form);
        echo $this->form()->closeTag(); ?>
    </div>
</div>
