<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Nyshu - Pasteles'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <!--Let browser know website is optimized for mobile-->
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, media=screen,projection')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <!--Import materialize.css-->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/materialize.css'))
    ; ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/materialize.js'))
        ->prependFile($this->basePath('js/init.js'))
        ->prependFile($this->basePath('js/jquery-2.1.1.min.js'))
    ; ?>

</head>
<body>
<!--
<nav class="purple" role="navigation">
    <div class="row">
        <div class="col s2 offset-s10" id="module_list">
            <ul>
                <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_welcome'>Bienvenido <?php //echo $_SESSION['user_name']; ?></a></li>
            </ul>
        </div>
        <ul id='dropdown_welcome' class='dropdown-content'>
            <li><a href="<?php //echo $this->url('panel-login', array('action' => 'logout')) ?>">Cerrar sesión</a></li>
        </ul>
    </div>
</nav>
-->
<nav class="purple" role="navigation">
    <div class="nav-wrapper container">
        <ul class="left hide-on-med-and-down">
            <li><a href="<?php echo $this->url('panel-categoria') ?>">&nbsp;<?php echo $this->translate('Categoría') ?></a></li>
            <li><a href="<?php echo $this->url('panel-producto') ?>">&nbsp;<?php echo $this->translate('Producto') ?></a></li>
            <li><a href="<?php echo $this->url('panel-producto-foto') ?>">&nbsp;<?php echo $this->translate('Photo de Producto') ?></a></li>
        </ul>
        <ul class="right">
            <li><a class="navbar_dropdown" href="javascript: void(0)" data-activates='dropdown_welcome'>Bienvenido <?php echo $_SESSION['user_name']; ?></a></li>
        </ul>
        <br>
        <ul id="nav-mobile" class="side-nav">
            <li><a href="<?php echo $this->url('panel-categoria') ?>">&nbsp;<?php echo $this->translate('Categoría') ?></a></li>
            <li><a href="<?php echo $this->url('panel-producto') ?>">&nbsp;<?php echo $this->translate('Producto') ?></a></li>
            <li><a href="<?php echo $this->url('panel-producto-foto') ?>">&nbsp;<?php echo $this->translate('Photo de Producto') ?></a></li>
        </ul>
        <ul id='dropdown_welcome' class='dropdown-content'>
            <li><a href="<?php echo $this->url('panel-login', array('action' => 'logout')) ?>">Cerrar sesión</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
</div> <!-- /container -->
<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            &copy; Copyright 2015 - - <?php echo date('Y') ?> by<a class="purple-text text-lighten-2" href="http://nyshu.com.mx"> Nyshu</a> - <?php echo $this->translate('All rights reserved.') ?>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
<script type="text/javascript">
    $('.navbar_dropdown').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: false, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: false // Displays dropdown below the button
    });
</script>
