<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Nyshu - Pasteles'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <!--Let browser know website is optimized for mobile-->
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, media=screen,projection')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <!--Import materialize.css-->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/mystyle.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/materialize.css'))
    ; ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/materialize.js'))
        ->prependFile($this->basePath('js/init.js'))
        ->prependFile($this->basePath('js/jquery-2.1.1.min.js'))
    ; ?>

</head>
<body>
<div>
    <?php echo $this->content; ?>

</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
