<script>
    function enviar_formulario(){
        document.formulario1.submit()
    }
</script>
<div class="row">
    <div class="col s3">
        <h4 class="grey-text">Productos</h4>
        <hr class="grey-text lighten-5">
        <ul class="collection">
            <?php foreach ($this->category as $categoryEntity):?>
                <?php
                switch($categoryEntity['category_name']){
                    case 'Pasteles':
                        $iconCategory = 'img/icon/cake22.png';
                        $producto = 'Pasteles';
                        break;
                    case 'Cupcakes':
                        $iconCategory = 'img/icon/cake26.png';
                        $producto = 'Cupcakes';
                        break;
                    case 'Brownies':
                        $iconCategory = 'img/icon/cake29.png';
                        $producto = 'Brownies';
                        break;
                    case 'Roscas':
                        $iconCategory = 'img/icon/donut4.png';
                        $producto = 'Roscas';
                        break;
                    case 'Gelatinas':
                        $iconCategory = 'img/icon/donut7.png';
                        $producto = 'Gelatinas';
                        break;
                    default:
                        $iconCategory = 'img/icon/han.png';
                        break;
                }
                ?>
                <!-- Menu lateral -->
                <a href="<?php echo $this->url('website-productos', array('id' => $categoryEntity['idcategory']))?>" class="collection-item"><?php echo $categoryEntity['category_name'] ?><span class="badge"><img src="<?php echo $this->basePath($iconCategory) ?>"></span></a>
            <?php endforeach;?>
        </ul>
    </div>

    <div class="col s9">
        <h4 class="grey-text"><?php echo isset($this->productos['category_name']) ? $this->productos['category_name'] : 'Todos'; ?></h4>
        <hr class="grey-text lighten-5">
        <?php foreach ($this->productos['product_collection'] as $productEntity):?>
            <div class="col s12 m4">
                <div class="icon-block">
                    <div class="col s12 center">
                        <div class="card">
                            <div class="card-image waves-effect waves-block waves-light">
                                <img class="activator" src="<?php echo $this->basePath('img/products/cake3.jpg') ?>">
                            </div>
                            <div class="card-content">
                                <span class="card-title activator grey-text text-darken-4"><?php echo htmlentities($productEntity['product_name'])?> <i class="mdi-navigation-more-vert right"></i></span>
                                <p><a class="purple-text" href="#">Más</a></p>
                            </div>
                            <div class="card-reveal">
                                <span class="card-title grey-text text-darken-4"><?php echo htmlentities($productEntity['product_name'])?> <i class="mdi-navigation-close right"></i></span>
                                <p><?php echo htmlentities($productEntity['product_description'])?></p>
                                <p>Precio: <?php echo htmlentities($productEntity['product_price'])?></p>
                                <p>Largo: <?php echo htmlentities($productEntity['product_long'])?> cm</p>
                                <p>Alto: <?php echo htmlentities($productEntity['product_high'])?> cm</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
    </div>
</div>