<?php $this->headTitle()->prepend('Contáctanos - Nyshu') ?>
<div class="container">
    <?php
    // Si el contacto fue guardado en nuestra base de datos.
    if($this->send):?>
        <div class="center-align col1" style="color: #47D598">
            <i class="medium mdi-toggle-check-box"></i>
        </div>
        <div class="center-align col s11 offset-s1" style="color: #47D598; font-size: 20px;">
            <span><?php echo "Gracias por contactarnos!"; ?></span>
            <br>
            <span><?php echo "En breve nos pondremos en contacto contigo."; ?></span>
            <div>&nbsp;</div>
        </div>
    <?php  endif;?>
    <div class="section">
        <blockquote style="border-left: 5px solid #64b5f6">
            <h4 class="grey-text text-darken-3">Levánta tu orden</h4>
        </blockquote>
        <!--   Form Section   -->
        <?php
        $form = $this->contactForm;
            $form->setAttribute('action', $this->url('website-contacto', array('action' => 'index')));
            $form->prepare();

            echo $this->form()->openTag($form);
            ?>
            <div class="row">
                <div class="input-field col s6">
                    <i class="mdi-action-account-circle prefix"></i>
                    <?php  echo $this->formText($form->get('contact_name')); ?>
                    <?php  echo $this->formLabel($form->get('contact_name'));
                    $showError=$this->formElementErrors($form->get('contact_name'));
                    if(!empty($showError)):
                        ?>
                        <div class="center-align col" style="color: #e57373">
                            <i class="mdi-content-report prefix"></i>
                        </div>
                        <div class="center-align col s11 offset-s1" style="color: #e57373">
                            <?php
                            echo $showError;
                            ?>
                        </div>
                    <?php  endif;?>
                </div>
                <div class="input-field col s6">
                    <i class="mdi-communication-email prefix"></i>
                    <?php  echo $this->formEmail($form->get('contact_email')); ?>
                    <?php  echo $this->formLabel($form->get('contact_email'));
                    $showError=$this->formElementErrors($form->get('contact_email'));
                    if(!empty($showError)):
                        ?>
                        <div class="center-align col" style="color: #e57373">
                            <i class="mdi-content-report prefix"></i>
                        </div>
                        <div class="center-align col s11 offset-s1" style="color: #e57373">
                            <?php
                            echo $showError;
                            ?>
                        </div>
                    <?php  endif;?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <i class="mdi-communication-call prefix"></i>
                    <?php  echo $this->formText($form->get('contact_phone')); ?>
                    <?php  echo $this->formLabel($form->get('contact_phone'));
                    $showError=$this->formElementErrors($form->get('contact_phone'));
                    if(!empty($showError)):
                    ?>
                    <div class="center-align col" style="color: #e57373">
                        <i class="mdi-content-report prefix"></i>
                    </div>
                    <div class="center-align col s11 offset-s1" style="color: #e57373">
                        <?php
                        echo $showError;
                        ?>
                    </div>
                    <?php  endif;?>
                </div>
                <div class="input-field col s6">
                    <i class="mdi-communication-comment prefix"></i>
                    <?php  echo $this->formText($form->get('contact_message')); ?>
                    <?php  echo $this->formLabel($form->get('contact_message'));
                    $showError=$this->formElementErrors($form->get('contact_message'));
                    if(!empty($showError)):
                        ?>
                        <div class="center-align col" style="color: #e57373">
                            <i class="mdi-content-report prefix"></i>
                        </div>
                        <div class="center-align col s11 offset-s1" style="color: #e57373">
                            <?php
                            echo $showError;
                            ?>
                        </div>
                    <?php  endif;?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <?php  echo $this->formCaptcha($form->get('validator')); ?>
                    </div>
                <div class="input-field col s6">
                    <?php
                    $showError=$this->formElementErrors($form->get('validator'));
                    if(!empty($showError)):
                        ?>
                        <div class="center-align col" style="color: #e57373">
                            <i class="mdi-content-report prefix"></i>
                        </div>
                        <div class="center-align col s11 offset-s1" style="color: #e57373">
                            <?php
                            echo $showError;
                            ?>
                        </div>
                    <?php  endif;?>
                </div>
            </div>
            <div class="input-field col s6">
                <?php  echo $this->formButton($form->get('submit')); ?>
            </div>
            <?php
            //echo $this->formCollection($form);
            echo $this->form()->closeTag(); ?>

        </div>
        <br>
        <br>
        <blockquote style="border-left: 5px solid #aed581">
            <h4 class="grey-text text-darken-3">Visítanos</h4>
        </blockquote>
        <p>
            Te invitamos a nuestra cafetería donde podrás disfrutar de ricas bebidas tanto calientes como frías, deliciosos postres tradicionales y de vanguardia disfrutando del acogedor ambiente de las instalaciones, que además cuentan con una pequeña biblioteca, juegos de mesa y proyecciones programadas.
        </p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3732.430820641482!2d-103.354059!3d20.692723!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8428b1e75a2c1b1b%3A0x1f95958f8e86bc19!2sMariano+Barcena+775%2C+Centro%2C+44100+Guadalajara%2C+Jal.!5e0!3m2!1ses!2smx!4v1433057322439" width="100%" height="400" frameborder="0" style="border:0"></iframe>
        <div class="center-align" style="font-weight: bold;">
            <p>Mariano Barcena 775, Centro, 44200 Guadalajara, Jal.</p>
        </div>
    </div>

</div>
