<?php
$title = 'Nuevo Elemento de texto';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->ElementoTextoForm;
$form->setAttribute('action', $this->url('panel-element-text', array('action' => 'nuevo')));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="row">
        <div class="input-field col s6 m6 l6">
            <i class="mdi-editor-border-color prefix"></i>
            <?php  echo $this->formText($form->get('elementtext_description')); ?>
            <?php  echo $this->formLabel($form->get('elementtext_description'));
            $showError=$this->formElementErrors($form->get('elementtext_description'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6 m6 l6">
            <?php echo $this->formSelect($form->get('elementtext_icon'));
            $showError=$this->formElementErrors($form->get('elementtext_icon'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="input-field col s6">
        <?php  echo $this->formButton($form->get('submit')); ?>
    </div>
<?php
//echo $this->formCollection($form);
echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
</script>
