<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center purple-text text-darken-3">Nyshu Pasteles</h1>
            <div class="row center">
                <h5 class="header col s12 light">Un moderno estilo de pasteles hecho a la medida.</h5>
            </div>
            <div class="row center">
                <a href="http://nyshu.com/contacts.phtml" id="download-button" class="btn-large waves-effect waves-light purple">Ordenar</a>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="<?php echo $this->basePath('img/index/pastelNuez.jpg') ?>" alt="pastelNuez img"></div>
</div>

<div class="container">
    <div class="section">

        <div class="row">
            <div class="col s12 center">
                <h3><i class="mdi-maps-store-mall-directory grey-text"></i></h3>
                <h4>Lo más vendido</h4>
                <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
            </div>
        </div>

    </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. </h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="<?php echo $this->basePath('img/index/chela31.jpg') ?>" alt="chela31 img "></div>
</div>

<div class="container">
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center grey-text"><i class="mdi-image-tonality"></i></h2>
                    <h5 class="center">Texto</h5>

                    <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center grey-text"><i class="mdi-social-group"></i></h2>
                    <h5 class="center">Texto</h5>

                    <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center grey-text"><i class="mdi-image-tag-faces"></i></h2>
                    <h5 class="center">Texto</h5>

                    <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="<?php echo $this->basePath('img/index/pastel15.jpg') ?>" alt="pastel15 img"></div>
</div>