<?php
$title = 'Eliminar categoría';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table class="table">
    <tr>
        <th>ID Categoría</th>
        <th>Nombre de Categoría</th>
    </tr>
        <tr>
            <td><?php echo $this->escapeHtml($categoria['idcategory']);?></td>
            <td><?php echo $this->escapeHtml($categoria['category_name']);?></td>
        </tr>
</table>
<?php
$url = $this->url('panel-categoria', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $categoria['idcategory']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>