<?php

$title = 'Mis Categorias';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('panel-categoria', array('action'=>'nuevo'));?>">Nueva Categoría</a>
</p>

<table class="table">
    <tr>
        <th>ID Categoría</th>
        <th>Nombre de Categoría</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    foreach ($categorias as $categoria) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($categoria['idcategory']);?></td>
            <td><?php echo $this->escapeHtml($categoria['category_name']);?></td>
            <td>
                <a href="<?php echo $this->url('panel-categoria',
                    array('action'=>'editar', 'id' => $categoria['idcategory']));?>">Editar</a>
                <a href="<?php echo $this->url('panel-categoria',
                    array('action'=>'eliminar', 'id' => $categoria['idcategory']));?>">Eliminar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>