<?php

$title = 'Mis Categorias';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('panel-categoria', array('action'=>'nuevo'));?>">Nueva Categoría</a>
</p>

<table class="table striped">
    <thead>
        <tr>
            <th>Nombre de Categoría</th>
            <th>Nombre del ícono</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($categorias as $categoria) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($categoria['category_name']);?></td>
                <td><?php echo $this->escapeHtml($categoria['category_icon']);?></td>
                <td>
                    <a href="<?php echo $this->url('panel-categoria',
                        array('action'=>'editar', 'id' => $categoria['idcategory']));?>">Editar</a>
                    <a href="<?php echo $this->url('panel-categoria',
                        array('action'=>'eliminar', 'id' => $categoria['idcategory']));?>">Eliminar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>