<?php $this->headTitle()->prepend('Acerca de Nyshu') ?>
<?php $this->headMeta()->appendName('description', 'Empresa familiar dedicada a generar experiencias inolvidables con los mejores postres y pasteles artísticos personalizados siempre con materia prima de calidad reflejada en nuestros productos.'); ?>
<div class="container-fluid DivSegidoDelMenuGeneral" style=" padding-top: 50px">
    <div class="container">
        <div id ="acerca-de" class="row">
            <div class="span12">
                <blockquote style="border-left: 5px solid #704E87">
                    <h3 class="grey-text text-darken-3">Nyshu</h3>
                </blockquote>
                <p class="flow-text">
                    Nyshu es una empresa familiar dedicada a generar experiencias inolvidables con los mejores postres y pasteles artísticos personalizados siempre con materia prima de calidad reflejada en nuestros productos.
                </p>
                <br/>
                <blockquote>
                    <h3 class="grey-text text-darken-3">Lo que hacemos</h3>
                </blockquote>
                <p class="flow-text">
                    Elaboramos los mejores y más delicados postres, así como pasteles con diseños exclusivos creados para ti ya que cada cliente y evento es único. Contamos también con mesas de postres, candy bar y mesa de botanas, con maravillosas decoraciones acordes al tema de tu evento para el deleite de tus invitados.
                </p>
                <br/>
                <blockquote style="border-left: 5px solid #26a69a;">
                    <h3 class="grey-text text-darken-3">La diferencia</h3>
                </blockquote>
                <p class="flow-text">
                    Para nosotros, la personalidad de nuestros clientes es muy importante, nuestros diseños los personalizamos con los gustos o detalles importantes para el homenajeado, haciendo que nuestras creaciones queden en su memoria y en la de sus invitados por mucho tiempo, creando una experiencia única, dejando a su vez, una parte de nosotros en cada obra ya que es realizada a mano con todo el cariño y paciencia que requiere.
                </p>
            </div>
        </div>
    </div>
</div>
