<?php
$title = 'Editar producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->productoForm;
    $form->setAttribute('action', $this->url(
        'panel-producto',
        array(
            'action' => 'editar',
            'id'     => $this->id,
        )
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>

    <div class="row">
        <div class="input-field col s6 m6 l6">
            <?php echo $this->formSelect($form->get('idcategory'));
            $showError=$this->formElementErrors($form->get('idcategory'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6 m6 l6">
            <i class="mdi-action-loyalty prefix"></i>
            <?php  echo $this->formText($form->get('product_name')); ?>
            <?php  echo $this->formLabel($form->get('product_name'));
            $showError=$this->formElementErrors($form->get('product_name'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6 m6 l6">
            <i class="mdi-file-file-upload prefix"></i>
            <?php echo $this->formRow($form->get('product_img'));
            $showError=$this->formElementErrors($form->get('product_img'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6 m6 l6">
            <i class="mdi-editor-border-color prefix"></i>
            <?php  echo $this->formText($form->get('product_description')); ?>
            <?php  echo $this->formLabel($form->get('product_description'));
            $showError=$this->formElementErrors($form->get('product_description'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="input-field col s6">
        <?php  echo $this->formButton($form->get('submit')); ?>
    </div>
    <?php
    echo $this->form()->closeTag();
?>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>