<?php
$title = 'Eliminar producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table class="table">
    <tr>
        <th>ID Producto</th>
        <th>ID Categoría</th>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Precio</th>
        <th>Largo</th>
        <th>Alto</th>
    </tr>
        <tr>
            <td><?php echo $this->escapeHtml($producto['idproduct']);?></td>
            <td><?php echo $this->escapeHtml($producto['idcategory']);?></td>
            <td><?php echo $this->escapeHtml($producto['product_name']);?></td>
            <td><?php echo $this->escapeHtml($producto['product_description']);?></td>
            <td><?php echo $this->escapeHtml($producto['product_price']);?></td>
            <td><?php echo $this->escapeHtml($producto['product_long']);?></td>
            <td><?php echo $this->escapeHtml($producto['product_high']);?></td>
        </tr>
</table>
<?php
$url = $this->url('panel-producto', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $producto['idproduct']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>