<?php
$title = 'Eliminar producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>¿Estás seguro que deseas eliminar el elemento?</p>
<table class="table">
    <tr>
        <th>Categoría</th>
        <th>Producto</th>
        <th>Descripción</th>
        <th>Imagen Url</th>
    </tr>
        <tr>
            <td><?php echo $this->escapeHtml($producto->getCategory()->getCategoryName());?></td>
            <td><?php echo $this->escapeHtml($producto->getProductName());?></td>
            <td><?php echo $this->escapeHtml($producto->getProductDescription());?></td>
            <td><?php echo $this->escapeHtml($producto->getProductImg());?></td>
        </tr>
</table>
<?php
$url = $this->url('panel-producto', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $producto->getIdproduct(); ?>" />
        <input type="submit" name="del" value="Si" />
        <input type="submit" name="del" value="No" />
    </div>
</form>