<?php

$title = 'Mis Productos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('panel-producto', array('action'=>'nuevo'));?>">Nuevo Producto</a>
</p>

<table class="table striped">
    <thead>
        <tr>
            <th>Categoría</th>
            <th>Producto</th>
            <th>Descripción</th>
            <th>Imagen Url</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($productos as $producto) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($producto->getCategory()->getCategoryName());?></td>
                <td><?php echo $this->escapeHtml($producto->getProductName());?></td>
                <td><?php echo $this->escapeHtml($producto->getProductDescription());?></td>
                <td><?php echo $this->escapeHtml($producto->getProductImg());?></td>
                <td>
                    <a href="<?php echo $this->url('panel-producto',
                        array('action'=>'editar', 'id' => $producto->getIdproduct()));?>">Editar</a>
                    <a href="<?php echo $this->url('panel-producto',
                        array('action'=>'eliminar', 'id' => $producto->getIdproduct()));?>">Eliminar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>