<?php
$title = 'Nuevo producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->productoForm;
$form->setAttribute('action', $this->url('panel-producto', array('action' => 'nuevo')));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="row">
        <div class="input-field col s6">
            <i class="mdi-action-view-list prefix"></i>
            <?php  echo $this->formText($form->get('idcategory')); ?>
            <?php  echo $this->formLabel($form->get('idcategory'));
            $showError=$this->formElementErrors($form->get('idcategory'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;
            if(!empty($Error)):
            ?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php
                echo $Error;
                ?>
            </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6">
            <i class="mdi-social-person-outline prefix"></i>
            <?php  echo $this->formText($form->get('product_name')); ?>
            <?php  echo $this->formLabel($form->get('product_name'));
            $showError=$this->formElementErrors($form->get('product_name'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6">
            <i class="mdi-editor-border-color prefix"></i>
            <?php  echo $this->formText($form->get('product_description')); ?>
            <?php  echo $this->formLabel($form->get('product_description'));
            $showError=$this->formElementErrors($form->get('product_description'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6">
            <i class="mdi-editor-attach-money prefix"></i>
            <?php  echo $this->formText($form->get('product_price')); ?>
            <?php  echo $this->formLabel($form->get('product_price'));
            $showError=$this->formElementErrors($form->get('product_price'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6">
            <i class="mdi-hardware-keyboard-tab prefix"></i>
            <?php  echo $this->formText($form->get('product_long')); ?>
            <?php  echo $this->formLabel($form->get('product_long'));
            $showError=$this->formElementErrors($form->get('product_long'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
        <div class="input-field col s6">
            <i class="mdi-editor-format-line-spacing prefix"></i>
            <?php  echo $this->formText($form->get('product_high')); ?>
            <?php  echo $this->formLabel($form->get('product_high'));
            $showError=$this->formElementErrors($form->get('product_high'));
            if(!empty($showError)):
                ?>
                <div class="center-align col" style="color: #e57373">
                    <i class="mdi-content-report prefix"></i>
                </div>
                <div class="center-align col s11 offset-s1" style="color: #e57373">
                    <?php
                    echo $showError;
                    ?>
                </div>
            <?php  endif;?>
        </div>
    </div>
    <div class="input-field col s6">
        <?php  echo $this->formButton($form->get('submit')); ?>
    </div>
<?php
//echo $this->formCollection($form);
echo $this->form()->closeTag(); ?>