<?php
$title = 'Eliminar fotos del producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>¿Estás seguro que deseas eliminar la foto?</p>
<table class="table">
    <thead>
    <tr>
        <th>Producto</th>
        <th>Foto (URL)</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $this->escapeHtml($productoFoto->getProduct()->getProductName());?></td>
            <td><?php echo $this->escapeHtml($productoFoto->getProductphotoImg());?></td>
        </tr>
    </tbody>
</table>
<?php
$url = $this->url('panel-producto-foto', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $productoFoto->getIdproductphoto(); ?>" />
        <input type="submit" name="del" value="Si" />
        <input type="submit" name="del" value="No" />
    </div>
</form>