<?php
$title = 'Eliminar fotos del producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete?</p>
<table class="table">
    <tr>
        <th>ID Foto</th>
        <th>ID Producto</th>
        <th>URL</th>
    </tr>
        <tr>
            <td><?php echo $this->escapeHtml($productoFoto['idproductphoto']);?></td>
            <td><?php echo $this->escapeHtml($productoFoto['idproduct']);?></td>
            <td><?php echo $this->escapeHtml($productoFoto['productphoto_img']);?></td>
        </tr>
</table>
<?php
$url = $this->url('panel-producto-foto', array(
    'action' => 'eliminar',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $productoFoto['idproductphoto']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>