<?php

$title = 'Mis Fotos de productos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('panel-producto-foto', array('action'=>'nuevo'));?>">Nueva Foto</a>
</p>

<table class="table striped">
    <thead>
        <tr>
            <th>Producto</th>
            <th>Foto (URL)</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($productoFotos as $productoFoto) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($productoFoto->getProduct()->getProductName());?></td>
                <td><?php echo $this->escapeHtml($productoFoto->getProductphotoImg());?></td>
                <td>
                    <a href="<?php echo $this->url('panel-producto-foto',
                        array('action'=>'eliminar', 'id' => $productoFoto->getIdproductphoto()));?>">Eliminar</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>