<?php
$title = 'Nueva foto para un producto';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1><?php
$form = $this->productoFotoForm;
$form->setAttribute('action', $this->url('panel-producto-foto', array('action' => 'nuevo')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="input-field col s6 m6 l6">
        <?php echo $this->formSelect($form->get('idproduct'));
        $showError=$this->formElementErrors($form->get('idproduct'));
        if(!empty($showError)):
            ?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php
                echo $showError;
                ?>
            </div>
        <?php  endif;?>
    </div>
    <div class="input-field col s6">
        <i class="mdi-file-file-upload prefix"></i>
       <?php echo $this->formRow($form->get('productphoto_img'));
        $showError=$this->formElementErrors($form->get('productphoto_img'));
        if(!empty($showError)):
            ?>
            <div class="center-align col" style="color: #e57373">
                <i class="mdi-content-report prefix"></i>
            </div>
            <div class="center-align col s11 offset-s1" style="color: #e57373">
                <?php
                echo $showError;
                ?>
            </div>
        <?php  endif;?>
    </div>
</div>
<div class="input-field col s6">
    <?php  echo $this->formButton($form->get('submit')); ?>
</div>
<?php
//echo $this->formCollection($form);
echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
</script>